import { image1, image2, image3, image4 } from "../assets/images/dummy";
import { IProduct } from "../models/dto/product.dto";

export const productList: IProduct[] = [
  {
    id: "1",
    cover: image1.src,
    images: [image1.src, image2.src, image3.src, image4.src],
    name: "Off-White",
    price: 775,
    subtitle: 'Out Of Office "Ooo"sneakers',
    priceSale: 58,
    status: "sale",
    description: `Energize your look with a fresh take on heritage adidas style. The adidas Daily 3.0 Shoes cut a classic profile with a modern suede upper. Your walk across campus or commute across town has never looked or felt this good.`,
    sold: 1,
    quantity: 1,
  },
  {
    id: "2",
    cover: image1.src,
    images: [image1.src, image2.src, image3.src, image4.src],
    name: "Off-White",
    price: 775,
    subtitle: 'Out Of Office "Ooo"sneakers',
    priceSale: 58,
    status: "sale",
    description: `Out Of Office "Ooo" sneakers`,
    sold: 1,
    quantity: 1,
  },
  {
    id: "3",
    cover: image1.src,
    images: [image1.src, image2.src, image3.src, image4.src],
    name: "Off-White",
    price: 775,
    subtitle: 'Out Of Office "Ooo"sneakers',
    priceSale: 58,
    status: "sale",
    description: `Out Of Office "Ooo" sneakers`,
    sold: 1,
    quantity: 1,
  },
  {
    id: "4",
    cover: image1.src,
    images: [image1.src, image2.src, image3.src, image4.src],
    name: "Off-White",
    price: 775,
    subtitle: 'Out Of Office "Ooo"sneakers',
    priceSale: 58,
    status: "sale",
    description: `Out Of Office "Ooo" sneakers`,
    sold: 1,
    quantity: 1,
  },
];
